### ISSUE TITLE
Space-travellers-hub: Setup Knanban Board

### ISSUE THREAD

**Issue by amare1990** [amare1990/space-travellers-hub#25]
**Total number of team members = 2**

**What we have done so far**
- We setup Github repo and used gitflow.
- We copied empty projects(classic) with empty columns from the `microverseinc React Group project'.
- We installed `jq` with ` sudo apt-get install jq` command.
- We copied all issues to our repo automatically.
- We deleted issues marked with `Team3`.

**Project link to the issues**
[Project link](https://github.com/users/amare1990/projects/7/views/1l)

**Comment by julie-ify** [comment]
Hi @amare1990,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

### You should include the link to the Kanban board in your issue above.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by andersonlebon** [comment]
### Hello team
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 :clap: :clap: :100: 

![nodding-yes](https://user-images.githubusercontent.com/65068771/143095390-344d1cb0-b853-4b91-8662-5d9049dc9e60.gif)

## To highlight :champagne: 
- Good commit history :heavy_check_mark: 
- Good PR description :heavy_check_mark: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
